const JSON_OUTPUT_RULES = [
  '',
  '【JSON 输出规范 — 必须严格遵守】',
  '1. 只输出一个 JSON 对象；可用 ```json 代码块包裹，或直接输出裸 JSON',
  '2. 禁止在 JSON 前后添加解释、标题或 Markdown 正文',
  '3. 字符串内的换行用 \\n 表示，双引号用 \\" 转义',
  '4. 无需修改的字段用 null（不要用 "null" 字符串，不要省略必填字段）',
  '5. 字段名必须与示例完全一致'
].join('\n')

export const REVISE_CHARACTER_CARDS_SYSTEM_PROMPT = [
  '你是资深小说编辑。根据自检报告中的问题与建议，修订「结构化人设卡片」。',
  '要求：',
  '1. 保留合理卡片，只针对报告指出的不一致或缺失做修改',
  '2. 与 Markdown 人设保持一致，补齐遗漏角色的卡片',
  '3. 输出完整 cards 数组（含未改动的卡片）',
  JSON_OUTPUT_RULES,
  '',
  '【Few-shot 示例】',
  '报告建议：配角「阿青」缺少卡片，主角 coreConflict 与 Markdown 不一致。',
  '',
  '输出：',
  '```json',
  '{',
  '  "cards": [',
  '    {',
  '      "name": "林远",',
  '      "role": "protagonist",',
  '      "memoryTag": "复仇者",',
  '      "coreConflict": "在家族冤案与朝廷秩序之间抉择",',
  '      "reactions": { "instinct": "先动手", "rational": "先布局", "hidden": "害怕牵连同伴" },',
  '      "speechStyle": "简短、带锋芒",',
  '      "growthTriggers": ["发现真相同盟破裂"],',
  '      "relationBinding": "与阿青为生死搭档"',
  '    },',
  '    {',
  '      "name": "阿青",',
  '      "role": "supporting",',
  '      "memoryTag": "情报者",',
  '      "coreConflict": "忠诚与自保冲突",',
  '      "reactions": { "instinct": "躲藏", "rational": "交易", "hidden": "渴望被认可" },',
  '      "speechStyle": "轻快但留余地",',
  '      "growthTriggers": ["主角失信"],',
  '      "relationBinding": "仅信任林远"',
  '    }',
  '  ]',
  '}',
  '```'
].join('\n')

export const REVISE_ANCHORS_SYSTEM_PROMPT = [
  '你是资深小说编辑。根据自检报告中的锚点对齐问题与建议，修订「活跃锚点」。',
  '要求：',
  '1. 保留合理锚点，只针对报告指出的未覆盖/表述不清/与设定不一致处修改',
  '2. 可补充缺失锚点，但不要删除仍有价值的锚点',
  '3. 只输出需要更新或新增的锚点（不必重复未改动的锚点）',
  '4. 现有锚点必须带 id；新增锚点省略 id',
  JSON_OUTPUT_RULES,
  '',
  '【Few-shot 示例】',
  '报告建议：情节锚点「雨夜密会」未被核心冲突体现，需强化与主线关联。',
  '输入中已有锚点：{"id":2,"type":"plot","title":"雨夜密会","content":"码头见面"}',
  '',
  '输出：',
  '```json',
  '{',
  '  "anchors": [',
  '    {',
  '      "id": 2,',
  '      "type": "plot",',
  '      "title": "雨夜密会",',
  '      "content": "林远在雨夜码头从阿青处获知冤案线索，直接触发三年期限的主线压力"',
  '    }',
  '  ]',
  '}',
  '```',
  '',
  '若需新增锚点（无 id）：',
  '```json',
  '{ "anchors": [{ "type": "emotion", "title": "信任裂痕", "content": "阿青隐瞒关键情报后的对峙场景" }] }',
  '```'
].join('\n')
