import { createApp } from 'vue'
import { createPinia } from 'pinia'

import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faAnchor,
  faArrowDown,
  faArrowLeft,
  faArrowUp,
  faBolt,
  faBook,
  faBookOpen,
  faBookmark,
  faBox,
  faBrain,
  faChartBar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboardCheck,
  faClock,
  faCode,
  faCopy,
  faCog,
  faDatabase,
  faDesktop,
  faDownload,
  faEdit,
  faEraser,
  faExclamationCircle,
  faExpand,
  faEye,
  faEyeSlash,
  faFeatherAlt,
  faFlask,
  faFire,
  faFont,
  faGem,
  faGlobe,
  faInfoCircle,
  faLightbulb,
  faListOl,
  faMoon,
  faPalette,
  faPaperclip,
  faPenNib,
  faPencilAlt,
  faPlus,
  faProjectDiagram,
  faRobot,
  faRotate,
  faSave,
  faSearch,
  faServer,
  faSliders,
  faSpinner,
  faStop,
  faSun,
  faThLarge,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faWifi
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faAnchor,
  faArrowDown,
  faArrowLeft,
  faArrowUp,
  faBolt,
  faBook,
  faBookOpen,
  faBookmark,
  faBox,
  faBrain,
  faChartBar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboardCheck,
  faClock,
  faCode,
  faCopy,
  faCog,
  faDatabase,
  faDesktop,
  faDownload,
  faEdit,
  faEraser,
  faExclamationCircle,
  faExpand,
  faEye,
  faEyeSlash,
  faFeatherAlt,
  faFlask,
  faFire,
  faFont,
  faGem,
  faGlobe,
  faInfoCircle,
  faLightbulb,
  faListOl,
  faMoon,
  faPalette,
  faPaperclip,
  faPenNib,
  faPencilAlt,
  faPlus,
  faProjectDiagram,
  faRobot,
  faRotate,
  faSave,
  faSearch,
  faServer,
  faSliders,
  faSpinner,
  faStop,
  faSun,
  faThLarge,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faWifi
)

import { initAppearanceSettings } from './services/appearanceSettings'
import App from './App.vue'
import router from './router'
import './assets/main.css'

initAppearanceSettings()

const app = createApp(App)
app.component('FontAwesomeIcon', FontAwesomeIcon)
app.use(createPinia())
app.use(router)
app.mount('#app')
