const STEP_TITLES: Record<string, string> = {
  character_cards_generate: 'AI 生成人设卡片',
  settings_overall_check: '设定整体自检',
  settings_character_check: '角色功能定位检查',
  settings_character_revise: '修订人设',
  settings_worldview_revise: '修订世界观',
  settings_conflict_revise: '修订核心冲突',
  settings_character_cards_revise: '修订人设卡片',
  settings_character_revise_all: '修订人设',
  settings_worldview_revise_all: '修订世界观',
  settings_conflict_revise_all: '修订核心冲突',
  settings_character_cards_revise_all: '修订人设卡片',
  settings_anchors_revise: '修订锚点',
  settings_anchors_revise_all: '修订锚点',
  settings_cross_character_revise: '跨设定 · 修订人设',
  settings_cross_worldview_revise: '跨设定 · 修订世界观',
  settings_cross_conflict_revise: '跨设定 · 修订核心冲突',
  settings_cross_character_revise_all: '跨设定 · 修订人设',
  settings_cross_worldview_revise_all: '跨设定 · 修订世界观',
  settings_cross_conflict_revise_all: '跨设定 · 修订核心冲突',
  body_generation: '生成正文',
  memory_extract: '提取叙事记忆',
  critique_dual_channel: '双通道批判',
  critique_apply_fixes: '批判修复',
  quality_diagnosis_ai: '章节质量诊断',
  anti_mean_surprise: '惊喜度评估',
  anti_mean_disruptor: '情节扰动建议',
  anti_mean_genre: '类型偏离分析',
  writer_block_inspiration: '随机灵感',
  writer_block_directions: '情节方向',
  writer_block_whatif: '角色假设实验',
  revision_checklist: '修订清单',
  ai_trace_polish: 'AI 痕迹润色',
  body_style_rewrite: '稿件优化（文风重写）',
  model_debate: '多模型辩论',
  model_debate_fusion: '辩论融合分析',
  incubator_diagnosis: '大岗诊断',
  incubator_expansion: '大岗扩写',
  incubator_nested: '嵌套结构预览',
  setting_ai_generate: 'AI 生成设定',
  style_generate: 'AI 生成文风',
  chapter_outline: '章节大纲',
  chapter_abc: 'ABC 结构解析',
  ai_intervention: 'AI 微指令',
  incubator_diagnose: '大岗诊断',
  incubator_diagnose_apply: '诊断修复入槽',
  incubator_variants: '大岗变体探索',
  incubator_reverse: '倒推大纲',
  incubator_anchors: '锚点收集',
  incubator_expand: '大岗扩写',
  incubator_benchmark: '对标分析',
  incubator_tone: '情感基调',
  incubator_frontstory: '前传设定',
  incubator_role_engine: '角色驱动轴',
  incubator_world_rules: '世界规则轴',
  incubator_emotion_curve: '情感曲线轴',
  incubator_ending_image: '终局意象',
  incubator_microinnovation: '微创新探索',
  settings_character: 'AI 生成人设',
  settings_worldview: 'AI 生成世界观',
  settings_conflict: 'AI 生成核心冲突',
  settings_idea: 'AI 生成故事方向',
  volume_chapters_batch: '批量生成分章'
}

export function resolveSessionTitle(step?: string, explicit?: string): string {
  if (explicit?.trim()) return explicit.trim()
  if (step && STEP_TITLES[step]) return STEP_TITLES[step]
  if (step) return step.replace(/_/g, ' ')
  return 'AI 任务'
}
