export { runPerplexityDetect, isPerplexityModelReady, disposePerplexityWorker, getSegmentMetrics } from './perplexity-service'
export type { SegmentDetectDetail, LabModelOverride } from './perplexity-service'
export { ensureModelReady, isModelReady, deleteModel, getModelStatus, listModels, switchModel, deleteModelById } from './model-manager'
export { DETECT_THRESHOLDS, FUSION_WEIGHTS, PERPLEXITY_MODELS, DEFAULT_MODEL_ID, getModelDef, getDetectThresholds, resolveDetectModelId } from './constants'
export { runHeuristicDetect, computeHeuristicAiScore } from './heuristic-detect'
export { isDegenerateApiLogprobs } from './api-perplexity'
export type { PerplexityModelDef } from './constants'
export { testApiConnection, computeViaApi, computeWholeViaApi } from './api-perplexity'
export type { TokenMetric } from './api-perplexity'
